version: "3.7"

services: 
  api:
    container_name: api-boilerplate
    build: ./api
    command: npm run start
    environment: 
      - PORT=3000
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    ports: 
      - ${API_HOST_PORT}:3000
      - ${API_HOST_DEBUG_PORT}:9229